const coffeeTheme = {
  primary: "#8B593E",
  background: "#FFF8F3",
  text: "#4A3428",
  border: "#E5D3B7",
  white: "#FFFFFF",
  textLight: "#9A8478",
  card: "#FFFFFF",
  shadow: "#000000",
  // Profile and dashboard specific colors
  error: "#DC2626",
  errorLight: "#FEF2F2",
  warning: "#F59E0B",
  warningText: "#111827",
  // New colors for modern chat interface
  online: "#4CAF50",
  offline: "#9A8478",
  divider: "#E5D3B7",
  messagePreview: "#9A8478",
  timestamp: "#B8A894",
  unreadBadge: "#D2691E",
  // Chat interface specific colors
  chatBubbleUser: "#8B593E",
  chatBubbleOther: "#F5EDE4",
  chatBubbleText: "#FFFFFF",
  chatBubbleTextOther: "#4A3428",
  inputBackground: "#F9F2E7",
  inputBorder: "#E5D3B7",
  sendButton: "#8B593E",
  messageTime: "#B8A894",
  chatHeaderBg: "#FFFFFF",
  // WhatsApp-style dark chat colors
  chatDarkBg: "#1C1C1C",
  chatPatternBg: "#242424",
  receivedBubble: "#2A2A2A",
  sentBubble: "#8B593E",
  receivedText: "#E5D3B7",
  sentText: "#FFFFFF",
  chatTimestamp: "#9A8478",
  messageInputBg: "#2A2A2A",
  messageInputText: "#E5D3B7",
  messageInputPlaceholder: "#9A8478",
  sendButtonBg: "#8B593E",
};

const forestTheme = {
  primary: "#2E7D32",
  background: "#E8F5E9",
  text: "#1B5E20",
  border: "#C8E6C9",
  white: "#FFFFFF",
  textLight: "#66BB6A",
  card: "#FFFFFF",
  shadow: "#000000",
  // Profile and dashboard specific colors
  error: "#DC2626",
  errorLight: "#FEF2F2",
  warning: "#F59E0B",
  warningText: "#111827",
  // New colors for modern chat interface
  online: "#4CAF50",
  offline: "#9E9E9E",
  divider: "#E0E0E0",
  messagePreview: "#757575",
  timestamp: "#9E9E9E",
  unreadBadge: "#FF5722",
  // Chat interface specific colors
  chatBubbleUser: "#2E7D32",
  chatBubbleOther: "#F0F0F0",
  chatBubbleText: "#FFFFFF",
  chatBubbleTextOther: "#000000",
  inputBackground: "#F8F8F8",
  inputBorder: "#E0E0E0",
  sendButton: "#2E7D32",
  messageTime: "#999999",
  chatHeaderBg: "#FFFFFF",
  // WhatsApp-style dark chat colors
  chatDarkBg: "#1C1C1C",
  chatPatternBg: "#242424",
  receivedBubble: "#2A2A2A",
  sentBubble: "#2E7D32",
  receivedText: "#C8E6C9",
  sentText: "#FFFFFF",
  chatTimestamp: "#66BB6A",
  messageInputBg: "#2A2A2A",
  messageInputText: "#C8E6C9",
  messageInputPlaceholder: "#66BB6A",
  sendButtonBg: "#2E7D32",
};

const purpleTheme = {
  primary: "#6A1B9A",
  background: "#F3E5F5",
  text: "#4A148C",
  border: "#D1C4E9",
  white: "#FFFFFF",
  textLight: "#BA68C8",
  card: "#FFFFFF",
  shadow: "#000000",
  // Profile and dashboard specific colors
  error: "#DC2626",
  errorLight: "#FEF2F2",
  warning: "#F59E0B",
  warningText: "#111827",
  // New colors for modern chat interface
  online: "#4CAF50",
  offline: "#BA68C8",
  divider: "#D1C4E9",
  messagePreview: "#BA68C8",
  timestamp: "#CE93D8",
  unreadBadge: "#E91E63",
  // Chat interface specific colors
  chatBubbleUser: "#6A1B9A",
  chatBubbleOther: "#EDE7F6",
  chatBubbleText: "#FFFFFF",
  chatBubbleTextOther: "#4A148C",
  inputBackground: "#F8F5FA",
  inputBorder: "#D1C4E9",
  sendButton: "#6A1B9A",
  messageTime: "#CE93D8",
  chatHeaderBg: "#FFFFFF",
  // WhatsApp-style dark chat colors
  chatDarkBg: "#1C1C1C",
  chatPatternBg: "#242424",
  receivedBubble: "#2A2A2A",
  sentBubble: "#6A1B9A",
  receivedText: "#D1C4E9",
  sentText: "#FFFFFF",
  chatTimestamp: "#BA68C8",
  messageInputBg: "#2A2A2A",
  messageInputText: "#D1C4E9",
  messageInputPlaceholder: "#BA68C8",
  sendButtonBg: "#6A1B9A",
};

const oceanTheme = {
  primary: "#0277BD",
  background: "#E1F5FE",
  text: "#01579B",
  border: "#B3E5FC",
  white: "#FFFFFF",
  textLight: "#4FC3F7",
  card: "#FFFFFF",
  shadow: "#000000",
  // Profile and dashboard specific colors
  error: "#DC2626",
  errorLight: "#FEF2F2",
  warning: "#F59E0B",
  warningText: "#111827",
  // New colors for modern chat interface
  online: "#4CAF50",
  offline: "#4FC3F7",
  divider: "#B3E5FC",
  messagePreview: "#4FC3F7",
  timestamp: "#81D4FA",
  unreadBadge: "#FF5722",
  // Chat interface specific colors
  chatBubbleUser: "#0277BD",
  chatBubbleOther: "#E3F2FD",
  chatBubbleText: "#FFFFFF",
  chatBubbleTextOther: "#01579B",
  inputBackground: "#F0F8FF",
  inputBorder: "#B3E5FC",
  sendButton: "#0277BD",
  messageTime: "#81D4FA",
  chatHeaderBg: "#FFFFFF",
  // WhatsApp-style dark chat colors
  chatDarkBg: "#1C1C1C",
  chatPatternBg: "#242424",
  receivedBubble: "#2A2A2A",
  sentBubble: "#0277BD",
  receivedText: "#B3E5FC",
  sentText: "#FFFFFF",
  chatTimestamp: "#4FC3F7",
  messageInputBg: "#2A2A2A",
  messageInputText: "#B3E5FC",
  messageInputPlaceholder: "#4FC3F7",
  sendButtonBg: "#0277BD",
};

const sunsetTheme = {
  primary: "#FF7E67",
  background: "#FFF3F0",
  text: "#2C1810",
  border: "#FFD5CC",
  white: "#FFFFFF",
  textLight: "#FFA494",
  card: "#FFFFFF",
  shadow: "#000000",
  // Profile and dashboard specific colors
  error: "#DC2626",
  errorLight: "#FEF2F2",
  warning: "#F59E0B",
  warningText: "#111827",
  // New colors for modern chat interface
  online: "#4CAF50",
  offline: "#FFA494",
  divider: "#FFD5CC",
  messagePreview: "#FFA494",
  timestamp: "#FFAB91",
  unreadBadge: "#F44336",
  // Chat interface specific colors
  chatBubbleUser: "#FF7E67",
  chatBubbleOther: "#FFF0EE",
  chatBubbleText: "#FFFFFF",
  chatBubbleTextOther: "#2C1810",
  inputBackground: "#FFF8F6",
  inputBorder: "#FFD5CC",
  sendButton: "#FF7E67",
  messageTime: "#FFAB91",
  chatHeaderBg: "#FFFFFF",
  // WhatsApp-style dark chat colors
  chatDarkBg: "#1C1C1C",
  chatPatternBg: "#242424",
  receivedBubble: "#2A2A2A",
  sentBubble: "#FF7E67",
  receivedText: "#FFD5CC",
  sentText: "#FFFFFF",
  chatTimestamp: "#FFA494",
  messageInputBg: "#2A2A2A",
  messageInputText: "#FFD5CC",
  messageInputPlaceholder: "#FFA494",
  sendButtonBg: "#FF7E67",
};

const mintTheme = {
  primary: "#00B5B5",
  background: "#E8F6F6",
  text: "#006666",
  border: "#B2E8E8",
  white: "#FFFFFF",
  textLight: "#66D9D9",
  card: "#FFFFFF",
  shadow: "#000000",
  // Profile and dashboard specific colors
  error: "#DC2626",
  errorLight: "#FEF2F2",
  warning: "#F59E0B",
  warningText: "#111827",
  // New colors for modern chat interface
  online: "#4CAF50",
  offline: "#66D9D9",
  divider: "#B2E8E8",
  messagePreview: "#66D9D9",
  timestamp: "#80E5E5",
  unreadBadge: "#FF5722",
  // Chat interface specific colors
  chatBubbleUser: "#00B5B5",
  chatBubbleOther: "#E0F7FA",
  chatBubbleText: "#FFFFFF",
  chatBubbleTextOther: "#006666",
  inputBackground: "#F0FAFA",
  inputBorder: "#B2E8E8",
  sendButton: "#00B5B5",
  messageTime: "#80E5E5",
  chatHeaderBg: "#FFFFFF",
  // WhatsApp-style dark chat colors
  chatDarkBg: "#1C1C1C",
  chatPatternBg: "#242424",
  receivedBubble: "#2A2A2A",
  sentBubble: "#00B5B5",
  receivedText: "#B2E8E8",
  sentText: "#FFFFFF",
  chatTimestamp: "#66D9D9",
  messageInputBg: "#2A2A2A",
  messageInputText: "#B2E8E8",
  messageInputPlaceholder: "#66D9D9",
  sendButtonBg: "#00B5B5",
};

const midnightTheme = {
  primary: "#2C3E50",
  background: "#F4F6F7",
  text: "#1A2530",
  border: "#D5D8DC",
  white: "#FFFFFF",
  textLight: "#7F8C8D",
  card: "#FFFFFF",
  shadow: "#000000",
  // Profile and dashboard specific colors
  error: "#DC2626",
  errorLight: "#FEF2F2",
  warning: "#F59E0B",
  warningText: "#111827",
  // New colors for modern chat interface
  online: "#4CAF50",
  offline: "#7F8C8D",
  divider: "#D5D8DC",
  messagePreview: "#7F8C8D",
  timestamp: "#95A5A6",
  unreadBadge: "#E74C3C",
  // Chat interface specific colors
  chatBubbleUser: "#2C3E50",
  chatBubbleOther: "#ECF0F1",
  chatBubbleText: "#FFFFFF",
  chatBubbleTextOther: "#1A2530",
  inputBackground: "#F8F9FA",
  inputBorder: "#D5D8DC",
  sendButton: "#2C3E50",
  messageTime: "#95A5A6",
  chatHeaderBg: "#FFFFFF",
  // WhatsApp-style dark chat colors
  chatDarkBg: "#1C1C1C",
  chatPatternBg: "#242424",
  receivedBubble: "#2A2A2A",
  sentBubble: "#2C3E50",
  receivedText: "#D5D8DC",
  sentText: "#FFFFFF",
  chatTimestamp: "#7F8C8D",
  messageInputBg: "#2A2A2A",
  messageInputText: "#D5D8DC",
  messageInputPlaceholder: "#7F8C8D",
  sendButtonBg: "#2C3E50",
};

const roseGoldTheme = {
  primary: "#E0BFB8",
  background: "#FDF6F5",
  text: "#4A3B38",
  border: "#F2D9D5",
  white: "#FFFFFF",
  textLight: "#C9A9A6",
  card: "#FFFFFF",
  shadow: "#000000",
  // Profile and dashboard specific colors
  error: "#DC2626",
  errorLight: "#FEF2F2",
  warning: "#F59E0B",
  warningText: "#111827",
  // New colors for modern chat interface
  online: "#4CAF50",
  offline: "#C9A9A6",
  divider: "#F2D9D5",
  messagePreview: "#C9A9A6",
  timestamp: "#D7B8B3",
  unreadBadge: "#FF6B6B",
  // Chat interface specific colors
  chatBubbleUser: "#E0BFB8",
  chatBubbleOther: "#FAF0EF",
  chatBubbleText: "#4A3B38",
  chatBubbleTextOther: "#4A3B38",
  inputBackground: "#FCF8F7",
  inputBorder: "#F2D9D5",
  sendButton: "#E0BFB8",
  messageTime: "#D7B8B3",
  chatHeaderBg: "#FFFFFF",
  // WhatsApp-style dark chat colors
  chatDarkBg: "#1C1C1C",
  chatPatternBg: "#242424",
  receivedBubble: "#2A2A2A",
  sentBubble: "#E0BFB8",
  receivedText: "#F2D9D5",
  sentText: "#4A3B38",
  chatTimestamp: "#C9A9A6",
  messageInputBg: "#2A2A2A",
  messageInputText: "#F2D9D5",
  messageInputPlaceholder: "#C9A9A6",
  sendButtonBg: "#E0BFB8",
};

export const THEMES = {
  coffee: coffeeTheme,
  forest: forestTheme,
  purple: purpleTheme,
  ocean: oceanTheme,
  sunset: sunsetTheme,
  mint: mintTheme,
  midnight: midnightTheme,
  roseGold: roseGoldTheme,
};

// 👇 change this to switch theme
export const COLORS = THEMES.forest;

// Common semi-transparent overlays used across components (kept separate from theme hues)
export const OVERLAY = {
  light: 'rgba(255,255,255,0.8)',
  dim: 'rgba(255,255,255,0.4)'
};

// Backdrop overlays (black with varying alpha) for scrims, modals, image masks
export const BACKDROP = {
  light: 'rgba(0,0,0,0.15)',
  medium: 'rgba(0,0,0,0.3)',
  dim: 'rgba(0,0,0,0.4)',
  dark: 'rgba(0,0,0,0.5)',
  heavy: 'rgba(0,0,0,0.75)'
};
